name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: npm
    - run: npm ci
    - run: npm run lint:js

  build:
    name: "Node ${{ matrix.node-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: install dependencies
      run: npm ci
    - run: npm run test:jest

  release-git-compat:
    name: "release-git@${{ matrix.release-git-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-git-version: ["^16.1.0"]

    steps:
    - uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
    - name: install dependencies
      run: npm ci
    - run: npm install --saveDev release-git@${{ matrix.release-git-version }}
    - run: npm run test:jest
